- name: Install packages
  become: true
  package:
    name:
    - httpd
    - chrony
    - wget
    - git
    - net-tools
    - curl
    - tree
    - unzip
    state: present

- name: Start and enable httpd service
  become: true
  service:
    name: httpd
    state: started
    enabled: true